version: '3'

services:
  postgresql:
    image: postgres:14
    container_name: postgresql
    ports:
      - "5430:5432"
    volumes:
      - ./script:/docker-entrypoint-initdb.d
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABSE: test
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: Passw0rd
    restart: always
volumes:
  db-store: